name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-build:
    name: Test and Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_suffix: linux
            binary_path: target/release/spreadsheet-read-mcp
          - os: macos-latest
            artifact_suffix: macos
            binary_path: target/release/spreadsheet-read-mcp
          - os: windows-latest
            artifact_suffix: windows
            binary_path: target/release/spreadsheet-read-mcp.exe
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Run tests
        run: cargo test --all --locked

      - name: Build release binary
        run: cargo build --release --locked

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: spreadsheet-read-mcp-${{ matrix.artifact_suffix }}
          path: ${{ matrix.binary_path }}
          if-no-files-found: error
